name: academiapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  cloud_firestore: 3.1.18
  firebase_core: 1.18.0
  firebase_auth: 3.3.20
  google_fonts: 3.0.1
  firebase_storage: 10.2.18
  google_sign_in: 5.3.3
  carousel_slider: 4.1.1
  intl: 0.17.0
  get_storage: 2.0.3
  date_picker_timeline: 1.2.3
  flutter_local_notifications: 9.6.1
  flutter_native_timezone: 2.0.0
  animated_bottom_navigation_bar: 1.0.0
  device_info: 2.0.3
  rxdart: 0.27.4
  image: 3.2.0
  animated_text_kit: 4.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

