// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB-gns0zCxN_DFcYn_S1Jo5q2cH0JxWjk',
    appId: '1:648768465871:web:ec1bca47d77f7b4eaf00ba',
    messagingSenderId: '648768465871',
    projectId: 'academi-app',
    authDomain: 'academi-app.firebaseapp.com',
    storageBucket: 'academi-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRHnl7muCqI6L724V3WQl0HDTtExuazJ0',
    appId: '1:648768465871:android:b712e5fe977cc69faf00ba',
    messagingSenderId: '648768465871',
    projectId: 'academi-app',
    storageBucket: 'academi-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_J5ejO0ZSAR3pUqHVCfrE_VTgO6yMwgc',
    appId: '1:648768465871:ios:6782929df9bcaffcaf00ba',
    messagingSenderId: '648768465871',
    projectId: 'academi-app',
    storageBucket: 'academi-app.appspot.com',
    iosClientId: '648768465871-qtpm4il4il9fl1riqb9uotk15v4hd6ge.apps.googleusercontent.com',
    iosBundleId: 'com.purboindra.academiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_J5ejO0ZSAR3pUqHVCfrE_VTgO6yMwgc',
    appId: '1:648768465871:ios:6782929df9bcaffcaf00ba',
    messagingSenderId: '648768465871',
    projectId: 'academi-app',
    storageBucket: 'academi-app.appspot.com',
    iosClientId: '648768465871-qtpm4il4il9fl1riqb9uotk15v4hd6ge.apps.googleusercontent.com',
    iosBundleId: 'com.purboindra.academiapp',
  );
}
